# financial_analysis_task:
#   description: >
#     Conduct an in-depth financial analysis of {ticker}, a constituent of the S&P 500. 
#     Evaluate its recent financial performance, revenue growth, profitability, balance 
#     sheet strength, and any notable risks or trends. Consider recent earnings reports, 
#     news, macroeconomic factors, and analyst sentiment.
#   expected_output: >
#     Conduct an in-depth financial analysis of {ticker}, a constituent of the S&P 500. 
#     Consider recent earnings reports, news, macroeconomic factors, and analyst
#     sentiment. At the end, provide a clear recommendation: "Yes, invest" or "No, 
#     do not invest", and summarize your reasoning.
#   agent: financial_analyst



final_decision_task:
  description: >
    Based on all the financial analyst outputs for each stock, compare their findings and 
    decide which stock(s) present the most promising investment opportunity for tomorrow. 
    Consider trends, volume, recent price movement, and the confidence in each analyst’s prediction.
  expected_output: >
    A clear and actionable investment recommendation. Specify one or more stocks to invest in,
    and justify your decision based on the analyst insights, technical patterns, and short-term expectations.
    Conclude whether each recommended stock is expected to go up or down.
  agent: final_decision