research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst


financial_analysis_task:
  description: >
    Conduct an in-depth financial analysis of {ticker}, a constituent of the S&P 500. 
    Evaluate its recent financial performance, revenue growth, profitability, balance 
    sheet strength, and any notable risks or trends. Consider recent earnings reports, 
    news, macroeconomic factors, and analyst sentiment.
  expected_output: >
    Conduct an in-depth financial analysis of {ticker}, a constituent of the S&P 500. 
    Consider recent earnings reports, news, macroeconomic factors, and analyst
    sentiment. At the end, provide a clear recommendation: "Yes, invest" or "No, 
    do not invest", and summarize your reasoning.
  agent: financial_analyst


# market_prediction_task:
#   description: >
#     Use the latest technical indicators for {ticker} to predict the market movement for the next trading day.
#     Consider RSI, MACD, SMA, and volume trends from Alpha Vantage.
#   expected_output: >
#     A brief prediction: Bullish / Bearish / Sideways
#     Include reasoning using the indicators (e.g., RSI < 30 implies oversold).
#   agent: prediction_bot
