stock_data_collector_task:
  description: >
    Analyze financial data, performance metrics, and valuation indicators for {tickers}.
    If you can't get the data or a tool fails try at most once and then ignore this and move on.
    Do not create dummy data or assume anything.
  expected_output: >
    A dictionary-like or markdown of the stock data you collected.
  agent: stock_data_collector

news_analysis_task:
  description: >
    Analyze news and sentiment for the {tickers} from financial perspective.
    1. Focus on what experienced stock traders would be interested in.
    2. Gauze the sentiment of people and the writer.
    3. Understand if any biasesness on opinion exists.
    4. Don't focus on the fluff, rather actual implication of the news.
    5. If you don't get news data, try at most 1 more time. Don't assume any news and ignore the failure.
  expected_output: >
    A markdown-formatted analysis of the news and sentiment for the stocks {tickers}.
  agent: news_analysis
  
web_analysis_task:
  description: >
    Scrape financial news from the web to gather data.
    Use your scraping capabilities to find relevant news articles and extract data.
    If you don't get any data, ignore it.
  expected_output: >
    A markdown-formatted summary of the scraped financial news articles.
  agent: web_analysis

final_decision_task:
  description: >
    Evaluate {tickers} stocks based on the data you received.
    Your final answer MUST include a recommendation about whether or not to invest in these stocks,
    and a short explanation based on its recent OHLC movement.
  expected_output: >
    A markdown-formatted investment recommendation for these companies that I mentioned based on stock trends.
  agent: final_decision
