# financial_analysis_task:
#   description: >
#     Conduct an in-depth financial analysis of {ticker}, a constituent of the S&P 500. 
#     Evaluate its recent financial performance, revenue growth, profitability, balance 
#     sheet strength, and any notable risks or trends. Consider recent earnings reports, 
#     news, macroeconomic factors, and analyst sentiment.
#   expected_output: >
#     Conduct an in-depth financial analysis of {ticker}, a constituent of the S&P 500. 
#     Consider recent earnings reports, news, macroeconomic factors, and analyst
#     sentiment. At the end, provide a clear recommendation: "Yes, invest" or "No, 
#     do not invest", and summarize your reasoning.
#   agent: financial_analyst



final_decision_task:
  description: >
    Use your stock analysis tool to evaluate AAPL and TSLA. Summarize the recent 5-day performance.
    Your final answer MUST include a recommendation about whether or not to invest in AAPL or TSLA,
    and a short explanation based on its recent OHLC movement.

  expected_output: >
    A markdown-formatted investment recommendation for AAPL based on stock trends.
